
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 22 19:05:44 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 19;
  public static final int PLUS = 26;
  public static final int PUTA = 14;
  public static final int ZAREZ = 10;
  public static final int CHAR = 32;
  public static final int GOTO = 22;
  public static final int TACKAZAREZ = 11;
  public static final int RETURN = 18;
  public static final int PODELJENO = 15;
  public static final int MINUSMINUS = 23;
  public static final int DVETACKE = 12;
  public static final int PROCENAT = 16;
  public static final int DESNAVITICASTA = 4;
  public static final int BOOLEAN = 31;
  public static final int BROJ = 30;
  public static final int IDENTIFIKATOR = 29;
  public static final int EOF = 0;
  public static final int TERNARNI = 28;
  public static final int DESNAZAGRADA = 6;
  public static final int LEVAZAGRADA = 5;
  public static final int PROG = 2;
  public static final int LEVAVITICASTA = 3;
  public static final int DESNAUGLASTA = 8;
  public static final int MINUS = 25;
  public static final int PLUSPLUS = 24;
  public static final int LEVAUGLASTA = 7;
  public static final int TACKA = 27;
  public static final int PRINT = 20;
  public static final int CONST = 9;
  public static final int error = 1;
  public static final int NEW = 21;
  public static final int JEDNAKO = 13;
  public static final int VOID = 17;
}

